/* 
 * Rakam API Documentation
 *
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Rakam.Client.Api;
using Rakam.Client.Model;
using Rakam.Client.Client;
using System.Reflection;

namespace Rakam.Client.Test
{
    /// <summary>
    ///  Class for testing CreatePrecomputedTable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreatePrecomputedTableTests
    {
        // TODO uncomment below to declare an instance variable for CreatePrecomputedTable
        //private CreatePrecomputedTable instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreatePrecomputedTable
            //instance = new CreatePrecomputedTable();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreatePrecomputedTable
        /// </summary>
        [Test]
        public void CreatePrecomputedTableInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreatePrecomputedTable
            //Assert.IsInstanceOfType<CreatePrecomputedTable> (instance, "variable 'instance' is a CreatePrecomputedTable");
        }

        /// <summary>
        /// Test the property 'Collections'
        /// </summary>
        [Test]
        public void CollectionsTest()
        {
            // TODO unit test for the property 'Collections'
        }
        /// <summary>
        /// Test the property 'Dimensions'
        /// </summary>
        [Test]
        public void DimensionsTest()
        {
            // TODO unit test for the property 'Dimensions'
        }
        /// <summary>
        /// Test the property 'Aggregations'
        /// </summary>
        [Test]
        public void AggregationsTest()
        {
            // TODO unit test for the property 'Aggregations'
        }
        /// <summary>
        /// Test the property 'Measures'
        /// </summary>
        [Test]
        public void MeasuresTest()
        {
            // TODO unit test for the property 'Measures'
        }
        /// <summary>
        /// Test the property 'TableName'
        /// </summary>
        [Test]
        public void TableNameTest()
        {
            // TODO unit test for the property 'TableName'
        }

    }

}
