/* 
 * Rakam API Documentation
 *
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Rakam.Client.Api;
using Rakam.Client.Model;
using Rakam.Client.Client;
using System.Reflection;

namespace Rakam.Client.Test
{
    /// <summary>
    ///  Class for testing RetentionQuery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RetentionQueryTests
    {
        // TODO uncomment below to declare an instance variable for RetentionQuery
        //private RetentionQuery instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RetentionQuery
            //instance = new RetentionQuery();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RetentionQuery
        /// </summary>
        [Test]
        public void RetentionQueryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RetentionQuery
            //Assert.IsInstanceOfType<RetentionQuery> (instance, "variable 'instance' is a RetentionQuery");
        }

        /// <summary>
        /// Test the property 'FirstAction'
        /// </summary>
        [Test]
        public void FirstActionTest()
        {
            // TODO unit test for the property 'FirstAction'
        }
        /// <summary>
        /// Test the property 'ReturningAction'
        /// </summary>
        [Test]
        public void ReturningActionTest()
        {
            // TODO unit test for the property 'ReturningAction'
        }
        /// <summary>
        /// Test the property 'Dimension'
        /// </summary>
        [Test]
        public void DimensionTest()
        {
            // TODO unit test for the property 'Dimension'
        }
        /// <summary>
        /// Test the property 'DateUnit'
        /// </summary>
        [Test]
        public void DateUnitTest()
        {
            // TODO unit test for the property 'DateUnit'
        }
        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Test]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }

    }

}
