/* 
 * Rakam API Documentation
 *
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Rakam.Client.Api;
using Rakam.Client.Model;
using Rakam.Client.Client;
using System.Reflection;

namespace Rakam.Client.Test
{
    /// <summary>
    ///  Class for testing UserSearchUsers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserSearchUsersTests
    {
        // TODO uncomment below to declare an instance variable for UserSearchUsers
        //private UserSearchUsers instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserSearchUsers
            //instance = new UserSearchUsers();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserSearchUsers
        /// </summary>
        [Test]
        public void UserSearchUsersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserSearchUsers
            //Assert.IsInstanceOfType<UserSearchUsers> (instance, "variable 'instance' is a UserSearchUsers");
        }

        /// <summary>
        /// Test the property 'Columns'
        /// </summary>
        [Test]
        public void ColumnsTest()
        {
            // TODO unit test for the property 'Columns'
        }
        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Test]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
        /// <summary>
        /// Test the property 'EventFilters'
        /// </summary>
        [Test]
        public void EventFiltersTest()
        {
            // TODO unit test for the property 'EventFilters'
        }
        /// <summary>
        /// Test the property 'Sorting'
        /// </summary>
        [Test]
        public void SortingTest()
        {
            // TODO unit test for the property 'Sorting'
        }
        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Test]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

    }

}
