/* 
 * Rakam API Documentation
 *
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Rakam.Client.Client;
using Rakam.Client.Api;
using Rakam.Client.Model;

namespace Rakam.Client.Test
{
    /// <summary>
    ///  Class for testing CollectApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CollectApiTests
    {
        private CollectApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CollectApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CollectApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // test 'IsInstanceOfType' CollectApi
            Assert.IsInstanceOfType(typeof(CollectApi), instance, "instance is a CollectApi");
        }

        
        /// <summary>
        /// Test BatchEvents
        /// </summary>
        [Test]
        public void BatchEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EventList eventList = null;
            //var response = instance.BatchEvents(eventList);
            //Assert.IsInstanceOf<int?> (response, "response is int?");
        }
        
        /// <summary>
        /// Test BulkEvents
        /// </summary>
        [Test]
        public void BulkEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EventList eventList = null;
            //var response = instance.BulkEvents(eventList);
            //Assert.IsInstanceOf<SuccessMessage> (response, "response is SuccessMessage");
        }
        
        /// <summary>
        /// Test BulkEventsRemote
        /// </summary>
        [Test]
        public void BulkEventsRemoteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BulkEventRemote bulkEventRemote = null;
            //var response = instance.BulkEventsRemote(bulkEventRemote);
            //Assert.IsInstanceOf<int?> (response, "response is int?");
        }
        
        /// <summary>
        /// Test CollectEvent
        /// </summary>
        [Test]
        public void CollectEventTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ModelEvent _event = null;
            //var response = instance.CollectEvent(_event);
            //Assert.IsInstanceOf<int?> (response, "response is int?");
        }
        
        /// <summary>
        /// Test CommitBulkEvents
        /// </summary>
        [Test]
        public void CommitBulkEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CommitBulkEvents commitBulkEvents = null;
            //var response = instance.CommitBulkEvents(commitBulkEvents);
            //Assert.IsInstanceOf<SuccessMessage> (response, "response is SuccessMessage");
        }
        
    }

}
