/* 
 * Rakam API Documentation
 *
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Rakam.Client.Client;
using Rakam.Client.Api;
using Rakam.Client.Model;

namespace Rakam.Client.Test
{
    /// <summary>
    ///  Class for testing EventexplorerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EventexplorerApiTests
    {
        private EventexplorerApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EventexplorerApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EventexplorerApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // test 'IsInstanceOfType' EventexplorerApi
            Assert.IsInstanceOfType(typeof(EventexplorerApi), instance, "instance is a EventexplorerApi");
        }

        
        /// <summary>
        /// Test AnalyzeEvents
        /// </summary>
        [Test]
        public void AnalyzeEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AnalyzeRequest analyzeRequest = null;
            //var response = instance.AnalyzeEvents(analyzeRequest);
            //Assert.IsInstanceOf<QueryResult> (response, "response is QueryResult");
        }
        
        /// <summary>
        /// Test CreatePrecomputedTable
        /// </summary>
        [Test]
        public void CreatePrecomputedTableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreatePrecomputedTable createPrecomputedTable = null;
            //var response = instance.CreatePrecomputedTable(createPrecomputedTable);
            //Assert.IsInstanceOf<PrecalculatedTable> (response, "response is PrecalculatedTable");
        }
        
        /// <summary>
        /// Test GetEventStatistics
        /// </summary>
        [Test]
        public void GetEventStatisticsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EventExplorerGetEventStatistics eventExplorerGetEventStatistics = null;
            //var response = instance.GetEventStatistics(eventExplorerGetEventStatistics);
            //Assert.IsInstanceOf<QueryResult> (response, "response is QueryResult");
        }
        
        /// <summary>
        /// Test GetExtraDimensions
        /// </summary>
        [Test]
        public void GetExtraDimensionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetExtraDimensions();
            //Assert.IsInstanceOf<Dictionary<string, List<string>>> (response, "response is Dictionary<string, List<string>>");
        }
        
    }

}
