/* 
 * Rakam API Documentation
 *
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Rakam.Client.Client;
using Rakam.Client.Api;
using Rakam.Client.Model;

namespace Rakam.Client.Test
{
    /// <summary>
    ///  Class for testing UseractionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UseractionApiTests
    {
        private UseractionApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UseractionApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UseractionApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // test 'IsInstanceOfType' UseractionApi
            Assert.IsInstanceOfType(typeof(UseractionApi), instance, "instance is a UseractionApi");
        }

        
        /// <summary>
        /// Test Batch
        /// </summary>
        [Test]
        public void BatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserEmailActionBatch userEmailActionBatch = null;
            //var response = instance.Batch(userEmailActionBatch);
            //Assert.IsInstanceOf<long?> (response, "response is long?");
        }
        
        /// <summary>
        /// Test Send
        /// </summary>
        [Test]
        public void SendTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserEmailActionSend userEmailActionSend = null;
            //var response = instance.Send(userEmailActionSend);
            //Assert.IsInstanceOf<bool?> (response, "response is bool?");
        }
        
    }

}
