/* 
 * Rakam API Documentation
 *
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Rakam.Client.Model
{
    /// <summary>
    /// CreatePrecomputedTable
    /// </summary>
    [DataContract]
    public partial class CreatePrecomputedTable :  IEquatable<CreatePrecomputedTable>
    {

        /// <summary>
        /// Gets or Sets Aggregations
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AggregationsEnum
        {
            
            /// <summary>
            /// Enum COUNT for "COUNT"
            /// </summary>
            [EnumMember(Value = "COUNT")]
            COUNT,
            
            /// <summary>
            /// Enum COUNTUNIQUE for "COUNT_UNIQUE"
            /// </summary>
            [EnumMember(Value = "COUNT_UNIQUE")]
            COUNTUNIQUE,
            
            /// <summary>
            /// Enum SUM for "SUM"
            /// </summary>
            [EnumMember(Value = "SUM")]
            SUM,
            
            /// <summary>
            /// Enum MINIMUM for "MINIMUM"
            /// </summary>
            [EnumMember(Value = "MINIMUM")]
            MINIMUM,
            
            /// <summary>
            /// Enum MAXIMUM for "MAXIMUM"
            /// </summary>
            [EnumMember(Value = "MAXIMUM")]
            MAXIMUM,
            
            /// <summary>
            /// Enum AVERAGE for "AVERAGE"
            /// </summary>
            [EnumMember(Value = "AVERAGE")]
            AVERAGE,
            
            /// <summary>
            /// Enum APPROXIMATEUNIQUE for "APPROXIMATE_UNIQUE"
            /// </summary>
            [EnumMember(Value = "APPROXIMATE_UNIQUE")]
            APPROXIMATEUNIQUE
        }

        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="aggregations", EmitDefaultValue=false)]
        public List<AggregationsEnum> Aggregations { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePrecomputedTable" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreatePrecomputedTable() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePrecomputedTable" /> class.
        /// </summary>
        /// <param name="Collections"> (required).</param>
        /// <param name="Dimensions"> (required).</param>
        /// <param name="Aggregations"> (required).</param>
        /// <param name="Measures"> (required).</param>
        /// <param name="TableName"> (required) (default to &quot;&quot;).</param>
        public CreatePrecomputedTable(List<string> Collections = null, List<string> Dimensions = null, List<AggregationsEnum> Aggregations = null, List<string> Measures = null, string TableName = null)
        {
            // to ensure "Collections" is required (not null)
            if (Collections == null)
            {
                throw new InvalidDataException("Collections is a required property for CreatePrecomputedTable and cannot be null");
            }
            else
            {
                this.Collections = Collections;
            }
            // to ensure "Dimensions" is required (not null)
            if (Dimensions == null)
            {
                throw new InvalidDataException("Dimensions is a required property for CreatePrecomputedTable and cannot be null");
            }
            else
            {
                this.Dimensions = Dimensions;
            }
            // to ensure "Aggregations" is required (not null)
            if (Aggregations == null)
            {
                throw new InvalidDataException("Aggregations is a required property for CreatePrecomputedTable and cannot be null");
            }
            else
            {
                this.Aggregations = Aggregations;
            }
            // to ensure "Measures" is required (not null)
            if (Measures == null)
            {
                throw new InvalidDataException("Measures is a required property for CreatePrecomputedTable and cannot be null");
            }
            else
            {
                this.Measures = Measures;
            }
            // to ensure "TableName" is required (not null)
            if (TableName == null)
            {
                throw new InvalidDataException("TableName is a required property for CreatePrecomputedTable and cannot be null");
            }
            else
            {
                this.TableName = TableName;
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="collections", EmitDefaultValue=false)]
        public List<string> Collections { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="dimensions", EmitDefaultValue=false)]
        public List<string> Dimensions { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="measures", EmitDefaultValue=false)]
        public List<string> Measures { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="tableName", EmitDefaultValue=false)]
        public string TableName { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreatePrecomputedTable {\n");
            sb.Append("  Collections: ").Append(Collections).Append("\n");
            sb.Append("  Dimensions: ").Append(Dimensions).Append("\n");
            sb.Append("  Aggregations: ").Append(Aggregations).Append("\n");
            sb.Append("  Measures: ").Append(Measures).Append("\n");
            sb.Append("  TableName: ").Append(TableName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CreatePrecomputedTable);
        }

        /// <summary>
        /// Returns true if CreatePrecomputedTable instances are equal
        /// </summary>
        /// <param name="other">Instance of CreatePrecomputedTable to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreatePrecomputedTable other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Collections == other.Collections ||
                    this.Collections != null &&
                    this.Collections.SequenceEqual(other.Collections)
                ) && 
                (
                    this.Dimensions == other.Dimensions ||
                    this.Dimensions != null &&
                    this.Dimensions.SequenceEqual(other.Dimensions)
                ) && 
                (
                    this.Aggregations == other.Aggregations ||
                    this.Aggregations != null &&
                    this.Aggregations.SequenceEqual(other.Aggregations)
                ) && 
                (
                    this.Measures == other.Measures ||
                    this.Measures != null &&
                    this.Measures.SequenceEqual(other.Measures)
                ) && 
                (
                    this.TableName == other.TableName ||
                    this.TableName != null &&
                    this.TableName.Equals(other.TableName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Collections != null)
                    hash = hash * 59 + this.Collections.GetHashCode();
                if (this.Dimensions != null)
                    hash = hash * 59 + this.Dimensions.GetHashCode();
                if (this.Aggregations != null)
                    hash = hash * 59 + this.Aggregations.GetHashCode();
                if (this.Measures != null)
                    hash = hash * 59 + this.Measures.GetHashCode();
                if (this.TableName != null)
                    hash = hash * 59 + this.TableName.GetHashCode();
                return hash;
            }
        }
    }

}
