/* 
 * Rakam API Documentation
 *
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Rakam.Client.Model
{
    /// <summary>
    /// QueryError
    /// </summary>
    [DataContract]
    public partial class QueryError :  IEquatable<QueryError>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryError" /> class.
        /// </summary>
        /// <param name="Message">Message.</param>
        /// <param name="SqlState">SqlState.</param>
        /// <param name="ErrorCode">ErrorCode.</param>
        /// <param name="ErrorLine">ErrorLine.</param>
        /// <param name="CharPositionInLine">CharPositionInLine.</param>
        public QueryError(string Message = null, string SqlState = null, int? ErrorCode = null, int? ErrorLine = null, int? CharPositionInLine = null)
        {
            this.Message = Message;
            this.SqlState = SqlState;
            this.ErrorCode = ErrorCode;
            this.ErrorLine = ErrorLine;
            this.CharPositionInLine = CharPositionInLine;
        }
        
        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }
        /// <summary>
        /// Gets or Sets SqlState
        /// </summary>
        [DataMember(Name="sqlState", EmitDefaultValue=false)]
        public string SqlState { get; set; }
        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>
        [DataMember(Name="errorCode", EmitDefaultValue=false)]
        public int? ErrorCode { get; set; }
        /// <summary>
        /// Gets or Sets ErrorLine
        /// </summary>
        [DataMember(Name="errorLine", EmitDefaultValue=false)]
        public int? ErrorLine { get; set; }
        /// <summary>
        /// Gets or Sets CharPositionInLine
        /// </summary>
        [DataMember(Name="charPositionInLine", EmitDefaultValue=false)]
        public int? CharPositionInLine { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QueryError {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  SqlState: ").Append(SqlState).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  ErrorLine: ").Append(ErrorLine).Append("\n");
            sb.Append("  CharPositionInLine: ").Append(CharPositionInLine).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as QueryError);
        }

        /// <summary>
        /// Returns true if QueryError instances are equal
        /// </summary>
        /// <param name="other">Instance of QueryError to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QueryError other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Message == other.Message ||
                    this.Message != null &&
                    this.Message.Equals(other.Message)
                ) && 
                (
                    this.SqlState == other.SqlState ||
                    this.SqlState != null &&
                    this.SqlState.Equals(other.SqlState)
                ) && 
                (
                    this.ErrorCode == other.ErrorCode ||
                    this.ErrorCode != null &&
                    this.ErrorCode.Equals(other.ErrorCode)
                ) && 
                (
                    this.ErrorLine == other.ErrorLine ||
                    this.ErrorLine != null &&
                    this.ErrorLine.Equals(other.ErrorLine)
                ) && 
                (
                    this.CharPositionInLine == other.CharPositionInLine ||
                    this.CharPositionInLine != null &&
                    this.CharPositionInLine.Equals(other.CharPositionInLine)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Message != null)
                    hash = hash * 59 + this.Message.GetHashCode();
                if (this.SqlState != null)
                    hash = hash * 59 + this.SqlState.GetHashCode();
                if (this.ErrorCode != null)
                    hash = hash * 59 + this.ErrorCode.GetHashCode();
                if (this.ErrorLine != null)
                    hash = hash * 59 + this.ErrorLine.GetHashCode();
                if (this.CharPositionInLine != null)
                    hash = hash * 59 + this.CharPositionInLine.GetHashCode();
                return hash;
            }
        }
    }

}
